# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd

# Load dataset
df = pd.read_csv("customer_sales_data.csv")

print("Dataset loaded successfully!\n")

# 1. First 5 rows
print("First 5 Rows:")
print(df.head())

# 2. Dataset information
print("\nDataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

# 3. Missing values
print("\nMissing Values:")
print(df.isnull().sum())

# 4. Descriptive statistics
print("\nDescriptive Statistics:")
print(df.describe())

# 5. Categorical analysis
print("\nGender Count:")
print(df["Gender"].value_counts())

print("\nCity Count:")
print(df["City"].value_counts())

print("\nProduct Category Count:")
print(df["Product_Category"].value_counts())

# 6. Business questions
print("\nBusiness Analysis:")

print("Average Purchase Amount:",
      round(df["Purchase_Amount"].mean(), 2))

print("Maximum Purchase Amount:",
      df["Purchase_Amount"].max())

print("Minimum Purchase Amount:",
      df["Purchase_Amount"].min())

print("Average Purchase Frequency:",
      round(df["Purchase_Frequency"].mean(), 2))

print("Average Rating:",
      round(df["Rating"].mean(), 2))

# 7. Total sales by product category
category_sales = df.groupby(
    "Product_Category"
)["Purchase_Amount"].sum().sort_values(ascending=False)

print("\nTotal Sales by Product Category:")
print(category_sales)

# 8. Total sales by city
city_sales = df.groupby(
    "City"
)["Purchase_Amount"].sum().sort_values(ascending=False)

print("\nTotal Sales by City:")
print(city_sales)

# 9. Outlier detection using IQR
q1 = df["Purchase_Amount"].quantile(0.25)
q3 = df["Purchase_Amount"].quantile(0.75)

iqr = q3 - q1

lower = q1 - 1.5 * iqr
upper = q3 + 1.5 * iqr

outliers = df[
    (df["Purchase_Amount"] < lower) |
    (df["Purchase_Amount"] > upper)
]

print("\nOutlier Analysis:")
print("Q1:", q1)
print("Q3:", q3)
print("IQR:", iqr)
print("Lower Limit:", lower)
print("Upper Limit:", upper)

print("\nPossible Outliers:")
print(outliers[["Customer_ID", "Purchase_Amount"]])

# 10. Correlation analysis
numeric_cols = [
    "Age",
    "Purchase_Amount",
    "Purchase_Frequency",
    "Rating"
]

correlation = df[numeric_cols].corr()

print("\nCorrelation Matrix:")
print(correlation)

# 11. Final findings
print("\n========== FINAL FINDINGS ==========")

print("Total Customers:", df["Customer_ID"].nunique())

print("Highest-Selling Category:",
      category_sales.index[0])

print("Highest-Sales City:",
      city_sales.index[0])

print("Number of Possible Outliers:",
      len(outliers))

# 12. Bonus Report
print("""
========== BONUS EDA REPORT ==========

1. The customer sales dataset was successfully analyzed.
2. Missing values were identified.
3. Descriptive statistics were calculated.
4. Customer distribution was analyzed by gender, city,
   and product category.
5. Sales were compared across product categories and cities.
6. Outliers were detected using the IQR method.
7. Correlation analysis was performed on numerical variables.

Conclusion:
EDA provides useful insights into customer purchasing
behavior and can support customer segmentation,
marketing decisions, and further data analysis.
""")